[tool.poetry]
name = "jinja101"
version = "0.1.0"
description = ""
authors = ["ubaumann <github@m.ubaumann.ch>"]

[tool.poetry.dependencies]
python = "^3.6"
flask = "^1.1.2"
pyaml = "^20.4.0"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
pylama = "^7.7.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
